### ISSUE TITLE
Cannot find module 'ionic-image-loader'

### ISSUE THREAD

**Issue by erpratap90** [zyra/ionic-image-loader#199]
In app.module.ts 
import { IonicImageLoader } from 'ionic-image-loader';

Shows error i reinstalled node modules also checked in the package.json entry exist 
"ionic-image-loader": "^6.3.0",

and in ionic serve getting error  Cannot find module 'ionic-image-loader' in main.ts 
<img width="1239" alt="screen shot 2018-09-21 at 5 20 54 pm" src="https://user-images.githubusercontent.com/2161147/45879853-9cb24000-bdc3-11e8-9213-00769817a313.png">

**Comment by madoBaker** [comment]
Couldn't replicate this error, can you please show me your app.module.ts file?

**Comment by ihadeed** [comment]
Make sure that `ionic-image-loader` exists in the `node_modules` directory. This issue is caused by Webpack not being able to locate the module. Might also worth trying to delete `package-lock.json` and `node_modules` and running `npm i` again.

**Comment by abdellahaski** [comment]
@ihadeed Actually I think that there is something wron with your plugin's package.json file

![image](https://user-images.githubusercontent.com/10819089/45934206-d4bbad80-bf92-11e8-96bd-b3b66999d00b.png)

you're telling it the the index.js file is in the dist directory but it is on the dist/src directory 
I manually changed that line to 
`"main": "dist/src/index.js",`
and the error disappeared

**Comment by ihadeed** [comment]
@abdellahaski sorry about that; you're right. There's an issue with the package. Forgot to update ts-config.json after upgrading to Angular 5. I just pushed a new version with a fix.

**Comment by edinsoncs** [comment]
I saw that they changed the organization of the project but the error remains the same
